---

#- name: Install Jenkins software
#  hosts: all
#  become: yes
# become_method: sudo

  #  tasks:
- name: Install dependencies
  package:
          name: "{{ item }}"
          state: latest

  with_items:
          - java-1.8.0-openjdk
          - git
          - wget
...


